//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.04 at 10:32:59 PM CEST 
//


package dani.java.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstrumentsAvaluacio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstrumentsAvaluacio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="instrumentAvaluacio" type="{http://www.xtec.cat/ProgramacioAula}InstrumentAvaluacio"/>
 *       &lt;/sequence>
 *       &lt;attribute name="criteriAvaluacio-ref" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstrumentsAvaluacio", propOrder = {
    "instrumentAvaluacio"
})
public class InstrumentsAvaluacio {

    @XmlElement(required = true)
    protected List<InstrumentAvaluacio> instrumentAvaluacio;
    @XmlAttribute(name = "criteriAvaluacio-ref")
    @XmlIDREF
    protected Object criteriAvaluacioRef;

    /**
     * Gets the value of the instrumentAvaluacio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instrumentAvaluacio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstrumentAvaluacio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstrumentAvaluacio }
     * 
     * 
     */
    public List<InstrumentAvaluacio> getInstrumentAvaluacio() {
        if (instrumentAvaluacio == null) {
            instrumentAvaluacio = new ArrayList<InstrumentAvaluacio>();
        }
        return this.instrumentAvaluacio;
    }

    /**
     * Gets the value of the criteriAvaluacioRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCriteriAvaluacioRef() {
        return criteriAvaluacioRef;
    }

    /**
     * Sets the value of the criteriAvaluacioRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCriteriAvaluacioRef(Object value) {
        this.criteriAvaluacioRef = value;
    }

}
