//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.05 at 04:44:22 PM CEST 
//


package dani.java.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dani.java.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProgramacioAula_QNAME = new QName("http://www.xtec.cat/ProgramacioAula", "programacioAula");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dani.java.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resum }
     * 
     */
    public Resum createResum() {
        return new Resum();
    }

    /**
     * Create an instance of {@link Contingut }
     * 
     */
    public Contingut createContingut() {
        return new Contingut();
    }

    /**
     * Create an instance of {@link ActivitatEnsenyamentAprenentatge }
     * 
     */
    public ActivitatEnsenyamentAprenentatge createActivitatEnsenyamentAprenentatge() {
        return new ActivitatEnsenyamentAprenentatge();
    }

    /**
     * Create an instance of {@link ActivitatsEnsenyamentAprenentatge }
     * 
     */
    public ActivitatsEnsenyamentAprenentatge createActivitatsEnsenyamentAprenentatge() {
        return new ActivitatsEnsenyamentAprenentatge();
    }

    /**
     * Create an instance of {@link UnitatFormativa }
     * 
     */
    public UnitatFormativa createUnitatFormativa() {
        return new UnitatFormativa();
    }

    /**
     * Create an instance of {@link Continguts }
     * 
     */
    public Continguts createContinguts() {
        return new Continguts();
    }

    /**
     * Create an instance of {@link ResultatAprenentatge }
     * 
     */
    public ResultatAprenentatge createResultatAprenentatge() {
        return new ResultatAprenentatge();
    }

    /**
     * Create an instance of {@link ResultatsAprenentatge }
     * 
     */
    public ResultatsAprenentatge createResultatsAprenentatge() {
        return new ResultatsAprenentatge();
    }

    /**
     * Create an instance of {@link CriteriAvaluacio }
     * 
     */
    public CriteriAvaluacio createCriteriAvaluacio() {
        return new CriteriAvaluacio();
    }

    /**
     * Create an instance of {@link InstrumentsAvaluacio }
     * 
     */
    public InstrumentsAvaluacio createInstrumentsAvaluacio() {
        return new InstrumentsAvaluacio();
    }

    /**
     * Create an instance of {@link Titular }
     * 
     */
    public Titular createTitular() {
        return new Titular();
    }

    /**
     * Create an instance of {@link NucliFormatiu }
     * 
     */
    public NucliFormatiu createNucliFormatiu() {
        return new NucliFormatiu();
    }

    /**
     * Create an instance of {@link Modul }
     * 
     */
    public Modul createModul() {
        return new Modul();
    }

    /**
     * Create an instance of {@link NuclisFormatius }
     * 
     */
    public NuclisFormatius createNuclisFormatius() {
        return new NuclisFormatius();
    }

    /**
     * Create an instance of {@link ProgramacioAula }
     * 
     */
    public ProgramacioAula createProgramacioAula() {
        return new ProgramacioAula();
    }

    /**
     * Create an instance of {@link Cicle }
     * 
     */
    public Cicle createCicle() {
        return new Cicle();
    }

    /**
     * Create an instance of {@link InstrumentAvaluacio }
     * 
     */
    public InstrumentAvaluacio createInstrumentAvaluacio() {
        return new InstrumentAvaluacio();
    }

    /**
     * Create an instance of {@link CriterisAvaluacio }
     * 
     */
    public CriterisAvaluacio createCriterisAvaluacio() {
        return new CriterisAvaluacio();
    }

    /**
     * Create an instance of {@link UnitatsFormatives }
     * 
     */
    public UnitatsFormatives createUnitatsFormatives() {
        return new UnitatsFormatives();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramacioAula }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xtec.cat/ProgramacioAula", name = "programacioAula")
    public JAXBElement<ProgramacioAula> createProgramacioAula(ProgramacioAula value) {
        return new JAXBElement<ProgramacioAula>(_ProgramacioAula_QNAME, ProgramacioAula.class, null, value);
    }

}
