//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.04 at 10:32:59 PM CEST 
//


package dani.java.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for TipusProva.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipusProva">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Prova teorica"/>
 *     &lt;enumeration value="Prova practica"/>
 *     &lt;enumeration value="Altres"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TipusProva {

    @XmlEnumValue("Altres")
    ALTRES("Altres"),
    @XmlEnumValue("Prova practica")
    PROVA_PRACTICA("Prova practica"),
    @XmlEnumValue("Prova teorica")
    PROVA_TEORICA("Prova teorica");
    private final String value;

    TipusProva(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipusProva fromValue(String v) {
        for (TipusProva c: TipusProva.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
